# Generated by Django 4.2.13 on 2024-06-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appactivity',
            new_name='app_activit_user_id_8d36f3_idx',
            old_name='accounts_ap_user_id_c86038_idx',
        ),
        migrations.AlterModelTable(
            name='appactivity',
            table='app_activity',
        ),
    ]
